### ISSUE TITLE
No output/not working from a clean venv install

### ISSUE THREAD

**Issue by tmplt** [SquishyStrawberry/httyd-bots#1]
```
$ git clone https://github.com/SquishyStrawberry/httyd-bots.git
$ virtualenv -p /usr/bin/python3 httyd-bots/
$ cd httyd-bots
$ pip3 install -r requirements.txt
$ cd Cloudjumper/ && python3 setup.py install
$ cd ../Thornado/ && python3 setup.py install
$ cd ../Cloudjumper/ && python3 -m cloudjumper
```

Zero output. `python3 --version` gives `Python 3.2.3`

Updated to Python 3.4.3, output is given:

```
$ python3 -m cloudjumper
/home/user/bots/irc/httyd-bots/bin/python3: Error while finding spec for 'cloudjumper.__main__' (<class 'ImportError'>: My other module 'https://github.com/SquishyStrawberry/python-irc-helper/' is needed, please download it.); 'cloudjumper' is a package and cannot be directly executed
```

**Comment by SquishyStrawberry** [comment]
Please give me the output of pip3 freeze, or if pip3 is not present, pip freeze.

**Comment by tmplt** [comment]
```
$ pip3 freeze
beautifulsoup4==4.3.2
cloudjumper==1.0
irc-helper==1.0
praw==2.1.21
requests==2.7.0
six==1.9.0
thornado==1.0
update-checker==0.11
```

**Comment by SquishyStrawberry** [comment]
This is an odd issue, as everything works correctly on my machine.
Please wait 2-3 days for me to acquire a DVD and make an install of your os, which I know to be Debian 7.
I will then test everything, and tell you my result.
If I find the same issue, I will try and debug it.
In the meantime, another thing that would help, would be to run `python3 -v -m cloudjumper` and tell me all the output.

**Comment by tmplt** [comment]
It's well... almost a 1k line output, so I'm linking it externally: https://bpaste.net/show/4a1e28ed7fcf

**Comment by SquishyStrawberry** [comment]
Please open httyd-bots/Cloudjumper/cloudjumper/cloudjumper.py and look for the line which contains `return message`.
Go a line before that, and add `; print(message)`. (On the same line.)

**Comment by tmplt** [comment]
There is no `return message` anywhere in `cloudjumper.py`.

**Comment by SquishyStrawberry** [comment]
You are correct. I'm sorry. 
Well then, go ahead and add these lines in the Cloudjumper class. ( I assume you know how to do that. )

```
def get_block(self, *args, **kwargs):  
    msg = super().get_block(*args, **kwargs)  
    print(msg)  
    return msg  
```

and tell me output, please.

**Comment by tmplt** [comment]
Issue resolved by fetching the latest version.
