### ISSUE TITLE
Cloudjumper ignores 'awesome_people' whitelist

### ISSUE THREAD

**Issue by okisiroki** [SquishyStrawberry/httyd-bots#2]
Usernames added or removed from the 'awesome_people' config are not taken to account, even after bot reboot.

**Comment by SquishyStrawberry** [comment]
While I know what you might mean, there are two different issues.
1. If you're trying to use it to OP people, you actually need to add the nick to auto_admin, or do `/msg {bot_nick} add_flag {to_admin} admin`.
2. The feature were the people in awesome_people had special greetings is temporarily removed, and will be readded in the future.
