### ISSUE TITLE
Global / Admin commands not working

### ISSUE THREAD

**Issue by okisiroki** [SquishyStrawberry/httyd-bots#3]
Admin commands such as `Cloudjumper! purge_commands` do not work for whitelisted people. (`Doesn't match` in terminal)

`Cloudjumper! list_commands` does not work. (`Doesn't match` in terminal) (I'm not sure if other global commands work or not)

**Comment by SquishyStrawberry** [comment]
Issue is due to user error, as the command is actually `/msg {bot_nick} list_commands` (Which sends a private message to the bot with the contnet "list_commands"), not `Cloudjumper! list_commands` in global/private chat.
