### ISSUE TITLE
Toothless reports Imgur links as "Imgur"

### ISSUE THREAD

**Issue by okisiroki** [SquishyStrawberry/httyd-bots#5]
Toothless should ignore Imgur links [without a title]\* all together.

**Comment by SquishyStrawberry** [comment]
This is actually incorrect; For some links, such as `https://imgur.com/gallery/DmhAmrE`, it does report a title. I will look into this anyways.

**Comment by okisiroki** [comment]
I'm referring to Imgur links without a title
